#! /bin/bash

if [ $EUID -ne 0 ]
    then echo "run as root"
    exit
fi

DAEMON_DIR="/etc/systemd/system/"

case $1 in
    start)
        sudo systemctl start ws_server
        sudo systemctl start http_server
        ;;
    stop)
        sudo systemctl stop ws_server
        sudo systemctl stop http_server
        ;;
    status)
        sudo systemctl status ws_server
        sudo systemctl status http_server
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
esac
